// Auto-generated by scripts/fetch-team-photos.py. Do not hand-edit.
window.TEAM = [
  {
    "name": "Matthew Thomson",
    "slug": "matthew-thomson",
    "file": "matthew-thomson.png"
  },
  {
    "name": "Abdelhalim Dadouche",
    "slug": "abdelhalim-dadouche",
    "file": "abdelhalim-dadouche.jpg"
  },
  {
    "name": "Andrew Weaver",
    "slug": "andrew-weaver",
    "file": "andrew-weaver.jpg"
  },
  {
    "name": "Michael Shtelma",
    "slug": "michael-shtelma",
    "file": "michael-shtelma.jpg"
  },
  {
    "name": "Nikolay Manchev",
    "slug": "nikolay-manchev",
    "file": "nikolay-manchev.jpg"
  },
  {
    "name": "Prashanth Babu",
    "slug": "prashanth-babu",
    "file": "prashanth-babu.png"
  },
  {
    "name": "Ryan Simpson",
    "slug": "ryan-simpson",
    "file": "ryan-simpson.jpg"
  },
  {
    "name": "Sepideh Ebrahimi",
    "slug": "sepideh-ebrahimi",
    "file": "sepideh-ebrahimi.jpg"
  },
  {
    "name": "Tomasz Bacewicz",
    "slug": "tomasz-bacewicz",
    "file": "tomasz-bacewicz.jpg"
  },
  {
    "name": "Athulya Ramamoorthy",
    "slug": "athulya-ramamoorthy",
    "file": "athulya-ramamoorthy.jpg"
  },
  {
    "name": "Bilal Obeidat",
    "slug": "bilal-obeidat",
    "file": "bilal-obeidat.jpg"
  },
  {
    "name": "Lars George",
    "slug": "lars-george",
    "file": "lars-george.jpg"
  },
  {
    "name": "Laurent Léturgez",
    "slug": "laurent-leturgez",
    "file": "laurent-leturgez.jpg"
  },
  {
    "name": "Louise Dilley",
    "slug": "louise-dilley",
    "file": "louise-dilley.jpg"
  },
  {
    "name": "Matthieu Lamairesse",
    "slug": "matthieu-lamairesse",
    "file": "matthieu-lamairesse.jpg"
  },
  {
    "name": "Silviu Tofan",
    "slug": "silviu-tofan",
    "file": "silviu-tofan.jpg"
  }
];
